In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:

a = np.zeros((8,8))

a[::2, ::2] = 1
a[1::2,1::2] = 1 

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
a = np.ones((4, 4), dtype=int)

print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
a[np.arange(4), np.arange(4)] = 0

print(a)

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


In [ ]:
a[0, 0] = 0
a[1, 1] = 0
a[2, 2] = 0
a[3, 3] = 0

print(a)

[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]


In [ ]:
for i in range(1000):
    a[i % 4, i % 4] = 0

print(a)

[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]


In [ ]:
a = np.ones((10,10))
for i in range(10):
    a[i, i] = 0
    a[i, 9-i] = 0
    print(a)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 1.

In [ ]:
result = np.where(a < 35, 'fail',
         np.where(a < 75, 'avg', 'good'))

print(result)

[['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']
 ['fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail' 'fail']]
