Home practuce numpy

In [1]:
import  numpy as np 

In [2]:
a = np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])     # 3 x 5 ka matrix hai ye 

In [3]:
a[0]

array([1, 2, 3, 4, 5])

In [4]:
a[:,2]   #ye maine  index ke hisab se 2column ko show krwaya hai 

array([3, 4, 5])

In [5]:
# abb dusra column ikal raha hu brother 

a[:,1]          #index ke hiasb se 1 column 

array([2, 3, 4])

In [6]:
# ab mai 6 ko pakd na chata hu  jo hamre array mai ahi

a[1,4]    # first row ki fourth column

np.int64(6)

In [7]:
a[2,4]    # second row ki fourth column 

np.int64(7)

In [8]:
# Sawal 4: Last row nikaal ([3 4 5 6 7]). Hint: -1 last se ginta hai.

a[-1]    # ye maine reverse  indexing ka use kiya hai  jo -1 se start hoti hai

array([3, 4, 5, 6, 7])

In [9]:
# Sawal 5: Number 4 nikaal jo row 2, column 1 mein hai. Sirf ek number.

a[2,1]   # Row  2 and column 1 ko hamne access kiya hai yaha pr 

np.int64(4)

In [10]:
# Sawal 6: Sirf last column nikaal ([5 6 7]).

a[ : , -1]             # ye sirf last  column hi nikala hai brother 

array([5, 6, 7])

In [11]:
# Sawal 7 (thoda tough): Pehli 2 rows aur pehle 3 columns nikaal. Output aisa aana chahiye:

# [[1 2 3]
#  [2 3 4]]

a[:2 ,:3]                #pele maine 2 rows nikali nad fir maine 3 column nikala 

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
# Sawal 8: Sirf last 2 columns nikaal, saari rows ke saath. Output:

# [[4 5]
#  [5 6]
#  [6 7]]

a[:,-2:]  # saari row : column ka matlb saari rows adn -1 index hotia hai last  ke elemet y elast row ya last colon ko accses kr ne lke liye revrese indexing bhi bolt ehi 

array([[4, 5],
       [5, 6],
       [6, 7]])

In [13]:
# Sawal 9: Beech ka element nikaal, matlab row 1, column 2. Sirf ek number.

a[1,2]

np.int64(4)

In [14]:
# Sawal 10 (tough): Row 1 aur row 2 ke column 1 se column 3 tak nikaal. Output: 
# [[3 4 5]
#  [4 5 6]]

a[1:3,1:4]      # 1:3 -> row 1 aur row 2 aayengi (start shamil hota hai, end wala 3 shamil nahi hota)
# 1:4 -> column 1, 2, 3 aayenge (start shamil hota hai, end wala 4 shamil nahi hota)
# Output -> [[3 4 5],
#            [4 5 6]]

array([[3, 4, 5],
       [4, 5, 6]])

In [15]:
# Sawal 11: Sirf row 0 aur row 2 ek saath nikaal. Output:

# [[1 2 3 4 5]
#  [3 4 5 6 7]]

a[[0,2]]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [16]:
# Sawal 12: Har dusra column nikaal (column 0, 2, 4), saari rows ke saath. Output:

# [[1 3 5]
#  [2 4 6]
#  [3 5 7]]

a[: , [0,2,4]]

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])

In [17]:
# Sawal 13: Poori array ki rows ka order ulta kar de (last row pehle). Output:

# [[3 4 5 6 7]
#  [2 3 4 5 6]
#  [1 2 3 4 5]]

a[: : -1 ]

# start:end:step format hai, start aur end khali = poori range
# step -1 = ulta chalo (last row se pehli row ki taraf)
# Output -> [[3 4 5 6 7],
#            [2 3 4 5 6],
#            [1 2 3 4 5]]

array([[3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [ ]:
Q # a = np.array([[1,2,3,4,5],
#                 [2,3,4,5,6],
#                 [3,4,5,6,7]])   

In [ ]:
# Sawal 14 (boss level): Sirf beech ka 2x2 block nikaal (row 0-1, column 1-2 wala):

# [[2 3]
#  [3 4]]

a[0:2, 1:3]
# 0:2 -> row 0 aur row 1 (end wala 2 shamil nahi hota)
# 1:3 -> column 1 aur column 2 (end wala 3 shamil nahi hota)
# Slice isliye lagaya kyunki rows aur columns dono continuous hain
# Output -> [[2 3],
#            [3 4]]


array([[2, 3],
       [3, 4]])

In [ ]:
# 📝 Q15. Find the sum of each row.
# Expected Output:

# [15 20 25]





In [42]:
# 📝 Q15. Ek saath 1st aur 3rd row ko access karo.

# Expected Output:

# [[1 2 3 4 5]
#  [3 4 5 6 7]]

a[[0,2]]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [ ]:
# Q.16. Print the 1st and 3rd columns of the matrix.

# Expected Output:

# [[1 3]
#  [2 4]
#  [3 5]]
   
a[:,[0,2]]     # jo maine list ke andr , coma lagaya wo ro type ka hai  and : lagata toh range ki woha se wah tak like , or  coliom ka matalb hai ki ye or ye jasi e [1 ,3]

# Logic yaad rakh:

# : → saari rows
# 0 → 1st column
# 2 → 3rd column
# [0, 2] → dono columns select karna

# Bhai, tera approach bilkul sahi tha. Bas 1 ki jagah 0 karna tha.

array([[1, 3],
       [2, 4],
       [3, 5]])