In [1]:
import numpy as np

In [2]:
a = np.array([[10, 25, 30], [45, 15, 60], [70, 35, 20]])

b = np.array([[1, 2, 3], [4, 1, 6], [7, 3, 2]])

In [3]:
a[a>25]

array([30, 45, 60, 70, 35])

In [4]:
a>25

array([[False, False,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [5]:
a.sum(axis=1)

array([ 65, 120, 125])

In [6]:
c = np.dot(a, b)
print(np.sum(result > 200))


NameError: name 'result' is not defined

In [ ]:
print(np.sum((a > 25) & (a < 60)))

3


In [ ]:
a[a>25] = 0
print(a)

[[10 25  0]
 [ 0 15  0]
 [ 0  0 20]]


In [ ]:
d = np.dot(a, b)
d[d > 200] = 0
print(np.mean(d == 0) * 100)

0.0


In [ ]:
c[c > 200] = 0
print(c)

print(c[c == 0])

print(len(c[c == 0]))

print(len(c[c == 0]) / len(c) * 100)

print(len(c))

print(c.shape)

print(c.shape[0])

print(c.shape[1])

print(len(c[c == 0]) / (c.shape[0] * c.shape[1]) * 100)


[[  0 135   0]
 [  0   0   0]
 [  0   0   0]]
[0 0 0 0 0 0 0 0]
8
266.66666666666663
3
(3, 3)
3
3
88.88888888888889


In [ ]:
np.random.randint(1,28)

22

In [ ]:
np.random.randint(1,28)

18

Homw work of day - 3 

In [ ]:
# q1. Design a game of 7 up and 7 down , rules are 2 dices are thrown and the numbers in those dices are added, if the number is greater or equal to 7 the player 2 wins else player 1 win


dice = np.random.randint(1, 7, 2)
total = np.sum(dice)


if total >= 7:
    print("Player 2 wins")
else:
    print("Player 1 wins")


Player 2 wins


In [ ]:
# q2. Design a code of bollywood game

# 1. गेम सेटअप (फिल्म का नाम और चांस)
movie = np.array(['S', 'H', 'O', 'L', 'A', 'Y'])
hidden = np.array(['_', '_', '_', '_', '_', '_'])
chances = 9  # BOLLYWOOD के 9 अक्षर

# 2. गेम का लूप
while chances > 0 and '_' in hidden:
    print("\nMovie:", hidden)
    guess = input("Enter a letter: ").upper()
    
    # अगर अक्षर फिल्म में है, तो खाली जगह पर भरें
    if guess in movie:
        hidden[movie == guess] = guess
    else:
        chances = chances - 1
        print("Wrong guess! Chances left:", chances)

# 3. फाइनल रिजल्ट
if '_' not in hidden:
    print("🎉 You Won!")
else:
    print("💥 Game Over!")



Movie: ['_' '_' '_' '_' '_' '_']


In [ ]:
# q3. Design a hangman game using turtle graphics where parts of the hanging man are drawn on every wrong guess

import turtle
import random

# 1. टर्टल स्क्रीन सेटअप (फाँसी का फंदा बनाने के लिए)
screen = turtle.Screen()
screen.setup(600, 600)
t = turtle.Turtle()
t.speed(0)
t.pensize(4)
t.hideturtle()

# फाँसी का स्टैंड (Gallows) बनाना
def draw_gallows():
    t.penup()
    t.goto(-150, -150)
    t.pendown()
    t.forward(100) # बेस
    t.backward(50)
    t.left(90)
    t.forward(250) # खंभा
    t.right(90)
    t.forward(100) # ऊपरी बीम
    t.right(90)
    t.forward(40)  # रस्सी

draw_gallows()

# गलत अनुमान पर एक-एक करके शरीर के हिस्से बनाना
def draw_hangman(wrong_guesses):
    if wrong_guesses == 1: # सिर (Head)
        t.right(90)
        t.circle(20)
        t.left(90)
        t.penup()
        t.forward(40)
        t.pendown()
    elif wrong_guesses == 2: # शरीर (Body)
        t.forward(60)
    elif wrong_guesses == 3: # बायाँ हाथ (Left Arm)
        t.backward(45)
        t.right(45)
        t.forward(35)
        t.backward(35)
        t.left(45)
    elif wrong_guesses == 4: # दायाँ हाथ (Right Arm)
        t.right(135)
        t.forward(35)
        t.backward(35)
        t.left(135)
        t.forward(45)
    elif wrong_guesses == 5: # बाईं टाँग (Left Leg)
        t.right(45)
        t.forward(45)
        t.backward(45)
        t.left(45)
    elif wrong_guesses == 6: # दाईं टाँग (Right Leg)
        t.right(135)
        t.forward(45)

# 2. गेम लॉजिक और वर्ड्स
words = ["PYTHON", "TURTLE", "MATRIX", "NUMPY", "CODING"]
secret_word = random.choice(words)
guessed_word = ["_" for _ in secret_word]
wrong_attempts = 0
guessed_letters = []

# 3. गेम का लूप
while wrong_attempts < 6 and "_" in guessed_word:
    print("\nWord:", " ".join(guessed_word))
    print(f"Chances left: {6 - wrong_attempts}")
    
    # टर्टल के इनपुट बॉक्स से या कंसोल से इनपुट लेना
    guess = screen.textinput("Hangman", "Enter a letter:").upper()
    
    if not guess or len(guess) != 1 or guess in guessed_letters:
        continue
        
    guessed_letters.append(guess)
    
    if guess in secret_word:
        for i in range(len(secret_word)):
            if secret_word[i] == guess:
                guessed_word[i] = guess
    else:
        wrong_attempts += 1
        draw_hangman(wrong_attempts)

# 4. फाइनल रिजल्ट
if "_" not in guessed_word:
    print(f"\n🎉 You Won! The word was: {secret_word}")
    t.penup()
    t.goto(-50, 150)
    t.write("You Won! 🎉", font=("Arial", 20, "bold"))
else:
    print(f"\n💥 Game Over! The word was: {secret_word}")
    t.penup()
    t.goto(-50, 150)
    t.write("Game Over! 💥", font=("Arial", 20, "bold"))

turtle.done()
