Numpy day one in carretronic day one 

In [ ]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,9,10]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  9 10]]


In [3]:
a[1:,1:]

array([[ 5,  6],
       [ 9, 10]])

In [4]:
a[2,1:]

array([ 9, 10])

In [5]:
a[2,1:]

array([ 9, 10])

In [6]:
a[2,:]   # second column ke sare le liya 

array([ 7,  9, 10])

In [ ]:
a[2,1:]  # second row  and 1st se leke numbe end number of column

array([ 9, 10])

In [8]:
a[0][1]

np.int64(2)

In [9]:
a[1][2]

np.int64(6)

In [10]:
a[2][0]

np.int64(7)

In [11]:
b = np.array([[1,2],[4,5],[7,9],[3,2]])
print(b) 

[[1 2]
 [4 5]
 [7 9]
 [3 2]]


In [12]:
b.shape

(4, 2)

In [13]:
b[:,1]

array([2, 5, 9, 2])

In [14]:
b[:,0]

array([1, 4, 7, 3])

In [15]:
b[2,0]

np.int64(7)

Class Home work date 27 - 09 - 2026

In [16]:
# NumPy Homework

# Create a 10 × 50 NumPy matrix and perform the following:

# 1. Try to access each row and each column.

# 2. Try to access the 10th row.

# 3. Access all the rows after the 7th row.

# 4. Try to access the 5th row.

# 5. Try to access all the columns and rows after the 5th row.

# 6. Try to access only the 4th row and 6th row with all the columns of the 10 × 5 matrix.

# 7. Try to access all the diagonal elements and all the anti-diagonal elements.

# 8.  Q. Print the matrix in reverse order.

In [17]:
# Create a 10 × 50 NumPy matrix and perform the following:

# Create a 10 x 50 NumPy matrix manually

c = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100],
    [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
    [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200],
    [201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250],
    [251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300],
    [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350],
    [351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400],
    [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450],
    [451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500]
])

print(c)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37  38  39  40  41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
   87  88  89  90  91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
  119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
  137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
  169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
  187 188 189 190 191 192 193 194 195 196 197 198 199 200]
 [201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
  219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
  237 238 239 240 241 24

In [18]:
c.shape

(10, 50)

In [19]:
# 1. Try to access each row and each column.

c[0]                                     #yaha pr each rows ko access kiya hu yani har rows ko brother 
c[1]
c[2]
c[3]
c[4]
c[5]
c[6]
c[7]
c[8]
c[9]

array([451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463,
       464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476,
       477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489,
       490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500])

In [20]:
# Access each column matlab har column access kr raha hu 

c[:, 0]
c[:, 1]
c[:, 2]
c[:, 3]
c[:, 4]
c[:, 5]
c[:, 6]
c[:, 7]
c[:, 8]
c[:, 9]
c[:, 10]
c[:, 11]
c[:, 12]
c[:, 13]
c[:, 14]
c[:, 15]
c[:, 16]
c[:, 17]
c[:, 18]
c[:, 19]
c[:, 20]
c[:, 21]
c[:, 22]
c[:, 23]
c[:, 24]
c[:, 25]
c[:, 26]
c[:, 27]
c[:, 28]
c[:, 29]
c[:, 30]
c[:, 31]
c[:, 32]
c[:, 33]
c[:, 34]
c[:, 35]
c[:, 36]
c[:, 37]
c[:, 38]
c[:, 39]
c[:, 40]
c[:, 41]
c[:, 42]
c[:, 43]
c[:, 44]
c[:, 45]
c[:, 46]
c[:, 47]
c[:, 48]
c[:, 49]

array([ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500])

In [21]:
# 2. Try to access the 10th row.

c[9]

array([451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463,
       464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476,
       477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489,
       490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500])

In [22]:
# 3. Access all the rows after the 7th row.

c[7]

array([351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400])

In [23]:
# 4. Try to access the 5th row.

c[5]

array([251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263,
       264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276,
       277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289,
       290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300])

In [24]:
# 5. Try to access all the columns and rows after the 5th row.

c[5:,:]

array([[251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263,
        264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276,
        277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289,
        290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300],
       [301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313,
        314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326,
        327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
        340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350],
       [351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
        364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
        377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
        390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400],
       [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
        414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
     

In [25]:
# 6. Try to access only the 4th row and 6th row with all the columns of the 10 × 50 matrix.

c[[3,5],:]    # abhi sirf 4th and 6th rows dikha rha ahi index  3 or 5 huva kukyi   indexing zerio se start hoti hai brother 

array([[151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
        177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
        190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200],
       [251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263,
        264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276,
        277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289,
        290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300]])

In [26]:
# 7. Try to access all the diagonal elements and all the anti-diagonal elements.


#Digonal 

# 7. Access all the diagonal elements

# 7. Access all the diagonal elements

print(c[0, 0])
print(c[1, 1])
print(c[2, 2])                    # top left to write and bottom ki taraf jata hai 
print(c[3, 3])
print(c[4, 4])
print(c[5, 5])
print(c[6, 6])
print(c[7, 7])
print(c[8, 8])
print(c[9, 9])


1
52
103
154
205
256
307
358
409
460


In [27]:
# Access all anti-diagonal elements

print(c[0, 49])  # Row 0, Column 49     #top right top bottom 
print(c[1, 48])  # Row 1, Column 48
print(c[2, 47])  # Row 2, Column 47
print(c[3, 46])  # Row 3, Column 46
print(c[4, 45])  # Row 4, Column 45
print(c[5, 44])  # Row 5, Column 44
print(c[6, 43])  # Row 6, Column 43
print(c[7, 42])  # Row 7, Column 42
print(c[8, 41])  # Row 8, Column 41
print(c[9, 40])  # Row 9, Column 40

50
99
148
197
246
295
344
393
442
491


In [28]:
# 8.  Q. Print the matrix in reverse order.

Day 2 Practice 

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,9,10]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  9 10]]


In [30]:
# 3x3 array create kiya
a = np.array([[1, 2, 3],[4, 5, 6],[8, 9, 10]])

# Har row ko 10, 20 aur 30 se multiply kiya
b = a * np.array([[10], [20], [30]])

# 3x3 output print kiya
print(b)

[[ 10  20  30]
 [ 80 100 120]
 [240 270 300]]


In [31]:
np.max(a)

np.int64(10)

In [32]:
np.min(a)

np.int64(1)

In [33]:
np.mean(a)

np.float64(5.333333333333333)

In [34]:
np.mean(a[:,0])

np.float64(4.333333333333333)

In [35]:

print(np.mean(a[:, [0, -1]]))

5.333333333333333


In [36]:
print(np.max(a[:,[0,-1]]))

10


In [37]:
np.max(a , axis = 0)

array([ 8,  9, 10])

In [38]:
np.min(a, axis = 1)

array([1, 4, 8])

In [39]:
a.T    

array([[ 1,  4,  8],
       [ 2,  5,  9],
       [ 3,  6, 10]])

In [40]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [24, 27, 30]])

In [41]:
a [:,0] = a[:,0] * 3

In [42]:
a[0,:] = a[0,:]*10

a[1,:] = a[1,:]*20

a[2,:] = a[2,:]* 20

In [43]:
a+3

array([[ 33,  23,  33],
       [243, 103, 123],
       [483, 183, 203]])

In [44]:
np.sqrt(a)

array([[ 5.47722558,  4.47213595,  5.47722558],
       [15.49193338, 10.        , 10.95445115],
       [21.9089023 , 13.41640786, 14.14213562]])

In [45]:
a+a

array([[ 60,  40,  60],
       [480, 200, 240],
       [960, 360, 400]])