In [1]:
import pandas as pd 

In [2]:
data = pd.read_csv("50_Startups (1).csv")

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score



print(data.head())
print(data.shape)
print(data.info())
print(data.isnull().sum())

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
(50, 5)
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     str    
 4   Profit           50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.1 KB
None
R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: 

In [4]:
data = pd.get_dummies(data, columns=["State"], drop_first=True)

X = data.drop("Profit", axis=1)
y = data["Profit"]

print(X.head())
print(y.head())

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10          False            True
1  162597.70       151377.59        443898.53          False           False
2  153441.51       101145.55        407934.54           True           False
3  144372.41       118671.85        383199.62          False            True
4  142107.34        91391.77        366168.42           True           False
0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64


In [5]:
#feature scaling 

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train)

[[ 0.34202149  0.22787678  0.12425038  1.36277029 -0.69388867]
 [ 1.36207849 -1.0974737   1.14990688  1.36277029 -0.69388867]
 [-0.71081297 -2.5770186  -0.34136825 -0.73379939 -0.69388867]
 [ 0.90611438  1.0172367   0.66890185 -0.73379939  1.44115338]
 [ 1.40997088 -0.09115403  1.30006861 -0.73379939  1.44115338]
 [ 1.20367103  0.96116332 -0.95248784 -0.73379939 -0.69388867]
 [-1.05285826 -1.34392538 -0.62843389  1.36277029 -0.69388867]
 [-1.61480906 -0.19649414  0.54106768  1.36277029 -0.69388867]
 [-1.642623    0.52691442 -2.07854935 -0.73379939 -0.69388867]
 [ 0.77885123  0.05437051  0.2294954  -0.73379939  1.44115338]
 [ 0.96515572 -0.45976843  0.61043134 -0.73379939 -0.69388867]
 [ 0.00687736  0.01677049  0.25215324 -0.73379939 -0.69388867]
 [-0.01361318 -0.80643974 -0.83912073 -0.73379939  1.44115338]
 [-0.66099544  1.34830937 -0.2199755  -0.73379939 -0.69388867]
 [-0.34996231  1.16416226 -1.30074144 -0.73379939  1.44115338]
 [ 1.85350175  0.58117289  2.08110569 -0.73379939  1.44

In [6]:
model = MLPRegressor(
    hidden_layer_sizes=(10, 10),
    max_iter=500,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Actual:", y_test.values)
print("Predicted:", y_pred)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

Actual: [134307.35  81005.76  99937.59  64926.08 125370.37  35673.41 105733.54
 107404.34  97427.84 122776.86]
Predicted: [ 64.17236659  82.66936377  68.63884386  58.50405085  94.52459545
 108.032488    34.84003447  57.89627802  63.04120255  75.89370653]
MSE: 10294122600.155666
R2 Score: -11.71205650749856


c:\Users\Hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [7]:
# ye mane matrix ke thorugh bhi kiyta hai brother 

X = [
    [165349.2, 136897.8, 471784.1],   # R&D, Administration, Marketing
    [162597.7, 151377.59, 443898.53], # second company ka data
    [153441.51, 101145.55, 407934.54] # third company ka data
]

W = [
    [0.1],   # R&D ka weight
    [0.2],   # Administration ka weight
    [0.3]    # Marketing ka weight
]

result = []   # final result store karne ke liye

for i in range(len(X)):       # ek-ek company/row ke liye loop
    total = 0                 # har company ka total 0 se start

    for j in range(len(W)):   # ek-ek feature ke liye loop
        total = total + X[i][j] * W[j][0]  # input × weight karke add

    result.append([total])    # final total ko result matrix mein store

print(result)                 # final matrix print

[[185449.70999999996], [179704.847], [157953.623]]


In [8]:
import pandas as pd
import numpy as np

data = pd.read_csv("50_Startups (1).csv")

X = pd.get_dummies(
    data[['R&D Spend', 'Administration', 'Marketing Spend', 'State']],
    columns=['State'],
    dtype=int
)

y = data['Profit']

wt_list = [40] * len(X.columns)
b = 40

h = 0.00001
alpha = 0.001

def mse_cal(X, y, wt_list, b):
    predicted = np.dot(X, wt_list) + b
    return sum((y - predicted) ** 2) / len(X)

grad_list = [0] * (len(X.columns) + 1)

for i in range(100):

    for i1 in range(len(X.columns) + 1):
        wt_list_new = wt_list.copy()

        if i1 == len(X.columns):
            f_wt_bh = mse_cal(X, y, wt_list, b + h)
            f_wb = mse_cal(X, y, wt_list, b)
            grad_list[i1] = (f_wt_bh - f_wb) / h

        else:
            wt_list_new[i1] = wt_list[i1] + h
            f_wt_b = mse_cal(X, y, wt_list_new, b)
            f_wb = mse_cal(X, y, wt_list, b)
            grad_list[i1] = (f_wt_b - f_wb) / h

    if sum(np.array(grad_list).round(6)) == 0:
        break

    else:
        for i2 in range(len(X.columns)):
            wt_list[i2] = wt_list[i2] - alpha * grad_list[i2]

        b = b - alpha * grad_list[len(X.columns)]

    print(grad_list)

[2883306212500.0, 3991854312499.9995, 8283735993749.999, 9937500.0, 11437499.999999998, 10881250.0, 32256249.999999996]
[-4.5035996273704953e+20, -5.6294995342131193e+20, -1.1258999068426239e+21, 0.0, 0.0, 0.0, 0.0]
